on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment details
        run: |
          uname -a
          ruby -v
          gem -v
          bundle -v

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Specify the Ruby version you need
          bundler-cache: true # Caches the 'vendor/bundle' directory

      - name: Add required platform
        run: bundle lock --add-platform x86_64-linux

      - name: Install dependencies
        run: bundle install

      - name: Set up script permissions
        run: |
          chmod +x script/bootstrap
          chmod +x script/cibuild

      - name: Build
        run: |
          script/bootstrap
          script/cibuild

      - name: Test
        run: script/cibuild
