name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8 
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler@>=2.7.8  # Update the version here

      - name: Run tests
        run: script/cibuild
