name: Update Listings

on:
  push:
    branches:
      - main

jobs:
  update-listings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # or the version you need

    - name: Install dependencies
      run: bundle install

    - name: Generate listings
      run: ruby generate_listings.rb
      env:
        WIKI_DIR: './wiki' # Set the environment variable to the correct path

    - name: Commit and push changes
  # Configure GitHub Actions bot
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
  # Check for changes
      if [ -n "$(git status --porcelain)" ]; then
  # Changes present
        git add _data/listings.json
        git add Gemfile.lock   
        git commit -m 'Update listings.json and Gemfile.lock'
        git push
      else
        # No changes
        echo "No changes to commit"
      fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}